[Compose] - feature/AA-1749-add-jetpack-compose
Spendesk/grapes-android pull request #102
Opened 2022-05-18 13:08 UTC by Scythe14

- Add compose necessary integrations and theming

2022-05-18 13:11 UTC, Scythe14 commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/Buttons.kt
> +@Composable
This is a first draft just to be used by the sample app, it will be reworked in a further PR

2022-05-18 15:02 UTC, kelianClerc requested changes
Popopopo this looks promising 😍

2022-05-18 15:02 UTC, kelianClerc commented on sample/src/main/java/com/spendesk/grapes/samples/home/fragments/ComposeFragment.kt
> +                Row {
You need to wrap the view with either `GrapesSampleTheme` (that would need to be created and that would just be a redeclaration of GrapesTheme) or either `GrapesTheme`. 
Like we do when using MaterialTheme composable

2022-05-18 15:02 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/theme/Colors.kt
> +)
This should be declared in the Theme.kt file
Colors.kt is to define Color variables : 
see : https://github.com/android/compose-samples/blob/main/Jetsnack/app/src/main/java/com/example/jetsnack/ui/theme/Color.kt
and 
https://github.com/android/compose-samples/blob/main/Jetsnack/app/src/main/java/com/example/jetsnack/ui/theme/Theme.kt

2022-05-18 15:47 UTC, Scythe14 commented on library-compose/src/main/java/com/spendesk/grapes/compose/theme/GrapesTheme.kt
> +    MaterialTheme
Mdrrr even after re-reading the PR I have not spotted this ! 😂 what aa noob, thx !

2022-05-18 15:49 UTC, Scythe14 commented on library-compose/src/main/java/com/spendesk/grapes/compose/theme/GrapesTheme.kt
> +    }
That surely will work better I guess, thanks !

2022-05-18 15:51 UTC, Scythe14 commented on library-compose/src/main/java/com/spendesk/grapes/compose/theme/Typography.kt
> +data class GrapesTypography constructor(
what do you mean by `this` ? Like the typography ?

2022-05-18 15:58 UTC, Scythe14 commented on sample/src/main/java/com/spendesk/grapes/samples/home/fragments/ComposeFragment.kt
> +                Row {
That would be better indeed, nice spot ! :)

2022-05-18 16:03 UTC, Scythe14 commented on library-compose/src/main/java/com/spendesk/grapes/compose/theme/Colors.kt
> +)
Ah yes this looks nice, centralise better the definitions in a single file of all our colors !

2022-05-18 16:38 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/theme/Typography.kt
> +data class GrapesTypography constructor(
It was more the constructor keyword

2022-05-18 16:39 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/theme/GrapesTheme.kt
> +}
The thing is, if another lib defines local with the same names it will create conflicts. So adding grapes in the name of it will certainly avoid conflicts

2022-05-19 09:37 UTC, Scythe14 commented on library-compose/src/main/java/com/spendesk/grapes/compose/theme/Typography.kt
> +data class GrapesTypography constructor(
It provides better flexibility if you need to add some other generic or internal values kind of like the defaultFontFamily for example

2022-05-19 09:53 UTC, kelianClerc approved these changes
Hop let's compose like Mozart

2022-06-09 06:45 UTC, kelianClerc approved these changes
Nice !

2022-06-09 06:50 UTC, merged