feat(compose) Add TopAppBar composable
Spendesk/grapes-android pull request #138
Opened 2022-12-29 22:12 UTC by jpbarbaud

# TopAppBar

## Composable

### GrapesTopAppBar

![Screenshot 2022-12-29 at 23 06 43](https://user-images.githubusercontent.com/112860634/210015511-a426e217-b544-4a91-b60d-e07452257558.png)

#### Code
```kotlin
GrapesTopAppBar(
                title = { GrapesTopAppBarTitleWithSubtitle(title = "Top app bar title", subTitle = "Top app bar subtitle") },
                navigationIcon = {
                    GrapesTopAppBarIconButton(icon = { GrapesTopAppBarBackIcon() }, onClick = {
                        Log.i("GrapesTopAppBar", "navigationIcon click")
                    })
                },
                actions = {
                    GrapesTopAppBarIconButton(icon = { GrapesTopAppBarMoreIcon() }, onClick = {
                        Log.i("GrapesTopAppBar", "action button click")
                    })
                },
            )
```

### GrapesExtendedTopAppBar

![Screenshot 2022-12-29 at 23 07 15](https://user-images.githubusercontent.com/112860634/210015535-69f237c8-861b-47ce-8ee6-34c4c55e1238.png)

#### Code
```kotlin
GrapesExtendedTopAppBar(
                title = { GrapesTopAppBarTitleWithSubtitle(title = "Top app bar title", subTitle = "Top app bar subtitle") },
                navigationIcon = {
                    GrapesTopAppBarIconButton(icon = { GrapesTopAppBarBackIcon() }, onClick = {
                        Log.i("GrapesTopAppBar", "navigationIcon click")
                    })
                },
                actions = {
                    GrapesTopAppBarIconButton(icon = { GrapesTopAppBarMoreIcon() }, onClick = {
                        Log.i("GrapesTopAppBar", "action button click")
                    })
                },
            )
```

2022-12-30 08:45 UTC, kelianClerc requested changes

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +        fontWeight = GrapesTheme.typography.titleL.fontWeight,
You should only specify Text's attribute: `style` with `GrapesTheme.typography.titleL`

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +            fontWeight = GrapesTheme.typography.bodyS.fontWeight,
same as previous one

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +    title: String, modifier: Modifier = Modifier
on param per line

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +    title: String, subTitle: String, modifier: Modifier = Modifier
on param per line

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +    icon: @Composable () -> Unit, modifier: Modifier = Modifier, onClick: () -> Unit = {}
same

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +        modifier = modifier.size(24.dp), imageVector = ImageVector.vectorResource(R.drawable.ic_arrow_back), contentDescription = "Back"
on perline + use a string res to set content description (you could even expose contentDescription in the method parameter)

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +        modifier = modifier.size(24.dp), imageVector = ImageVector.vectorResource(R.drawable.ic_more_vertical), contentDescription = "More"
same same

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +        modifier = modifier.size(24.dp), imageVector = ImageVector.vectorResource(R.drawable.ic_arrow_back), contentDescription = "Back"
I do not know the diff but I rather use painterResource for displaying drawables: 
`Icon(painter = painterResource(id = R.drawable.ic_arrow_back), contentDescription = "")`

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +                    .padding(bottom = 8.dp)
this padding is here to separate top app bars right?
If so you should rather do the following thing: 
```kotlin
Column(
            modifier = Modifier
                .fillMaxSize()
                .background(GrapesTheme.colors.mainNeutralLighter)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.spacedBy(8.dp)
        )
```
It will add a 8dp space between all items of the column :)

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +                    .fillMaxSize(),
weird it worked 🤔 
it should be fillMaxWidth() because you only want the toolbar to take all width available, not all height

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +                    .fillMaxSize(),
same for all the other samples

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +            modifier = Modifier,
not meeded

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +            modifier = modifier,
not `modifier = modifier` either specify a specific modifier or let Text use its default one

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +                    GrapesTopAppBarIconButton(icon = { GrapesTopAppBarBackIcon() }, onClick = {
params to different lines

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +fun GrapesExtendedTopAppBar(
Why is this needed? Is it used in the app?
 Bottom alignemnt for the title feels weird haha

2022-12-30 08:45 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +private val extendedTopAppBarHeight = 128.dp
https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md#singletons_constants_sealed-class-and-enum-class-values

2023-01-02 13:38 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +fun GrapesExtendedTopAppBar(
I followed the material 2 recommandations 
https://m2.material.io/components/app-bars-top
They don't recommande to truncate the title but use _Extended top app bar_
I also followed their UI guidelines.

If we update our component to material 3, we could use medium our large TopAppBar instead.

2023-01-02 13:39 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +    title: String, modifier: Modifier = Modifier
done

2023-01-02 13:40 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +        fontWeight = GrapesTheme.typography.titleL.fontWeight,
done

2023-01-02 13:41 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +    title: String, subTitle: String, modifier: Modifier = Modifier
done

2023-01-02 13:43 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +            modifier = Modifier,
done

2023-01-02 13:44 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +            modifier = modifier,
Ok, hard to remembering this rule :p

2023-01-02 13:44 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +            fontWeight = GrapesTheme.typography.bodyS.fontWeight,
done

2023-01-02 13:44 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +    icon: @Composable () -> Unit, modifier: Modifier = Modifier, onClick: () -> Unit = {}
Done

2023-01-02 14:01 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +        modifier = modifier.size(24.dp), imageVector = ImageVector.vectorResource(R.drawable.ic_arrow_back), contentDescription = "Back"
When we use a `Painter` argument, compose must detect what kind of drawable it face off, while using `imageVector`, compose will directly create a _rememberVectorPainter_.

Using `imageVector` seems to be more straightforward.

2023-01-02 14:02 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +        modifier = modifier.size(24.dp), imageVector = ImageVector.vectorResource(R.drawable.ic_more_vertical), contentDescription = "More"
done done

2023-01-02 14:06 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +                    .fillMaxSize(),
🤷 I replaced with `fillMaxWidth` just in case

2023-01-02 14:09 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +                    GrapesTopAppBarIconButton(icon = { GrapesTopAppBarBackIcon() }, onClick = {
done

2023-01-02 14:16 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/appbar/GrapesTopAppBar.kt
> +private val extendedTopAppBarHeight = 128.dp
thx, done.

2023-01-02 15:24 UTC, kelianClerc approved these changes

2023-01-02 15:36 UTC, merged