Feat(Compose) Add features and rework button to be more slot compliant
Spendesk/grapes-android pull request #143
Opened 2023-01-23 15:30 UTC by jpbarbaud

# Compose – Button

## Rework Buttons

## UI

![alert_button](https://user-images.githubusercontent.com/112860634/214079467-1abd0f9e-4cf4-4207-80a5-8e54a14ffa17.gif)
![link_button](https://user-images.githubusercontent.com/112860634/214079482-0fa72871-04b3-4b7d-834e-f845c293363e.gif)
![link_secondary_button](https://user-images.githubusercontent.com/112860634/214079488-435c86a4-90de-4d0c-9254-3452de250031.gif)
![primary_button](https://user-images.githubusercontent.com/112860634/214079493-98450005-48a0-4206-bbaa-da5291c0b142.gif)
![primary_small_button](https://user-images.githubusercontent.com/112860634/214079503-bc83d6ec-7c44-4a8d-be2e-c7ffd8c348e7.gif)
![secondary_button_small](https://user-images.githubusercontent.com/112860634/214079512-3e2e17b1-09f3-40ad-922d-774fb2d60d2b.gif)
![secondary_button](https://user-images.githubusercontent.com/112860634/214079516-d6936fe9-1234-4698-bbf1-fbaddeaa9803.gif)
![secondary_small_button](https://user-images.githubusercontent.com/112860634/214079534-9f174e61-d399-46ad-bfda-3b130a811d2e.gif)
![text_button](https://user-images.githubusercontent.com/112860634/214079541-b8be27d7-9fe1-40a2-951e-3227ddbb2060.gif)
![warning_button](https://user-images.githubusercontent.com/112860634/214079557-5bd05a00-91fb-49be-acf0-44b2e514b418.gif)

2023-01-26 10:57 UTC, kelianClerc requested changes

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButtonDefaults.kt
> +                TODO("DarkTheme Not implemented yet")
I would prefer using light colors which are not adapted rather than crashing if not lightTheme but as you prefer 🤷

2023-01-26 10:57 UTC, kelianClerc commented on sample/src/main/java/com/spendesk/grapes/samples/home/fragments/ComposeFragment.kt
> +                            modifier = Modifier,
not needed

2023-01-26 10:57 UTC, kelianClerc commented on sample/src/main/java/com/spendesk/grapes/samples/home/fragments/ComposeFragment.kt
> +                                text = "First Compose component test")
weird inlining

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
not needed

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/template/AskTemplate.kt
> +import androidx.compose.foundation.layout.*
wildcard ?

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +import androidx.compose.foundation.layout.*
wildcard?

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                if (showLoadingIndicator.not()) {
prefer using positive statement: 
if (showLoadsingIndication) {
CircularProgressIndicator
} else {
content
}

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
same

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +import androidx.compose.material.*
wildcard?

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +    ) {
not fan of that, the ripple is still occuring, it just has no color.
Passing a null onClick to the button when loading isn't enough ?

2023-01-26 10:57 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +    ) {
How do material does it when the button is disabled ?

2023-01-26 11:19 UTC, jpbarbaud commented on sample/src/main/java/com/spendesk/grapes/samples/home/fragments/ComposeFragment.kt
> +                            modifier = Modifier,
fixed

2023-01-26 11:19 UTC, jpbarbaud commented on sample/src/main/java/com/spendesk/grapes/samples/home/fragments/ComposeFragment.kt
> +                                text = "First Compose component test")
fixed

2023-01-26 13:48 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
Done

2023-01-26 13:48 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
Done

2023-01-26 13:48 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +                modifier = Modifier,
Done

2023-01-26 13:50 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +import androidx.compose.material.*
Fixed

2023-01-26 13:54 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +    ) {
You cannot pass null to onClick on a Button. but I already give empty lambda if `showLoadingIndicator` is given, but this still keep the ripple effect

2023-01-26 13:59 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +    ) {
But I found a better solution: 
by defining clickable Modifier without `indication` -> the ripple effect disappear

2023-01-30 13:07 UTC, kelianClerc approved these changes

2023-01-30 14:11 UTC, merged