Task/aa 2361 link secondary improvements
Spendesk/grapes-android pull request #149
Opened 2023-02-08 10:30 UTC by Scythe14

2023-02-08 13:50 UTC, jpbarbaud reviewed
Oops le fichier `.idea/inspectionProfiles/Project_Default.xml` ?

2023-02-08 13:51 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +    content: @Composable RowScope.() -> Unit
nit: it's possible to keep the trailing comma 😬 ?

2023-02-08 14:01 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +    leadingIcon: Painter? = null,
To be more splot compliant, icon should be added directly trought Content.
It would be better to create additional composable function like `GrapesButtonTextWithIcon`.

WDYT ?

2023-02-08 14:08 UTC, jpbarbaud requested changes
icon should be passed through content (see my comment)

2023-02-08 14:08 UTC, kelianClerc requested changes

2023-02-08 14:08 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +
this means the icons stays when the button is loading which shouldn't

2023-02-08 14:08 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +    leadingIcon: Painter? = null,
The slot api means that with the established base, you can put anything you want inside the content composable.
Icon shouldn't be defined here. 
It must be inside content

2023-02-08 14:08 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +    leadingIcon: Painter? = null,
Consider creating an overload of the base method which use the base method providing to content the icon and the actual content

2023-02-17 16:30 UTC, jpbarbaud commented
Reworked in https://github.com/Spendesk/grapes-android/pull/154

2023-02-17 16:30 UTC, closed without merging