feat(compose) Replace GrapesButton Component by GrapesButtonText
Spendesk/grapes-android pull request #153
Opened 2023-02-16 11:18 UTC by jpbarbaud

Replace `GrapesButton` composable with `GrapesButtonText`.
Make GrapesButton internal

## Before/Now

before
```kotlin
GrapesButton(
    buttonStyle  = GrapesButtonStyleDefaults.primary,
) {
    Text("blablabla")
}
```

Now
```kotlin
GrapesButtonText(
    text = "Button Primary Enabled",
    buttonStyle = GrapesButtonStyleDefaults.primary,
)
```

2023-02-16 15:37 UTC, kelianClerc requested changes

2023-02-16 15:37 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +fun GrapesButtonText(
move to a dedicated GrapesButtonText file ?

2023-02-16 15:37 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +internal fun GrapesButtonContent(
private ? This composable shouldn't be used by anyone except for GrapesTextButton ?

2023-02-16 15:37 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +internal fun GrapesButtonContentText(
same ?

2023-02-16 15:37 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +fun GrapesButtonText(
The naming can be confusing because on material, a Text Button is a button without background :/ 
What about continuing to use GrapesButton for the default button ?

2023-02-17 15:08 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +fun GrapesButtonText(
I'm ok with the naming, I will move files into another PR.  
Done

2023-02-17 15:09 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +internal fun GrapesButtonContent(
done

2023-02-17 15:09 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButton.kt
> +internal fun GrapesButtonContentText(
done

2023-02-17 15:14 UTC, kelianClerc approved these changes

2023-02-17 15:31 UTC, merged