feat(compose) Add GrapesButtonIcon
Spendesk/grapes-android pull request #154
Opened 2023-02-17 16:06 UTC by jpbarbaud

## GrapesCoreButton
- Add the possibility of adding a leading Icon

## Composables
- Create new GrapesButtonIcon

## Demo

⚠️  I fixed the icon sized for small buttons

### Primary
![primary](https://user-images.githubusercontent.com/112860634/219706311-302423bf-8a32-43ea-831a-123c6b9a097b.gif)

### Primary Small
![primary_small](https://user-images.githubusercontent.com/112860634/219706306-b1186941-558b-469f-b80a-ab2eb88dc4b2.gif)

### Secondary
![secondary](https://user-images.githubusercontent.com/112860634/219706326-ef762606-ecba-486f-9385-ea03e91a7669.gif)

### Secondary small
![secondary_small](https://user-images.githubusercontent.com/112860634/219706321-46e9fa3d-8e16-483b-b263-15b84c01f769.gif)

### Text
![text](https://user-images.githubusercontent.com/112860634/219706338-e391ce30-a02c-42fe-b03d-e0a0a27b9e19.gif)

### Text Small
![text_small](https://user-images.githubusercontent.com/112860634/219706335-192c1204-9747-42c1-bdb8-f37ee15b4a68.gif)

### Warning
![warning](https://user-images.githubusercontent.com/112860634/219706347-16b279cf-cadf-49f1-9d88-1a244402dbdc.gif)

### Error
![error](https://user-images.githubusercontent.com/112860634/219706284-775df311-8fd9-45ab-9fbe-b85242848f17.gif)

### Link primary
![link_primary](https://user-images.githubusercontent.com/112860634/219706296-b5da8c85-f54a-40c5-9ff6-f5da3dfd65d7.gif)

### Link secondary
![link_secondary](https://user-images.githubusercontent.com/112860634/219706301-d7f8597f-ebcb-4ae5-8a01-9aa808c7c1e7.gif)

2023-02-27 09:14 UTC, kelianClerc requested changes
+ on long text, icon is too close on fillmxsize
![Capture d’écran 2023-02-27 à 10 05 20](https://user-images.githubusercontent.com/26220096/221522187-15a8f785-daa0-43c9-868e-3d261a4985ff.png)

2023-02-27 09:14 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButtonIcon.kt
> +    val isFillMaxWidthWithContent =
this should be a paramneter of GrapesButtonStyleDefaults instead of refering to which GrapesButtonStyleDefaults is used

2023-02-27 09:14 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesCoreButton.kt
> +
This seems to be a lot of lines just to set a box 🤔 
Why not creating two different sub composables one for each case.
```
if (fill) {
FillComposable
} else {
RowComposable
}
```

Row is a basic: 
```
Row {
 leadingIcon()
 content()
 }
 ```
 and fill is: 
 ```
 Box() {
     Row() {
         leadingIcon()
         Spacer(weight = 1f)
     }
     Row() {
         Spacer(weight = 1f)
         content()
         Spacer(weight = 1f)
     }
}
```

Why do you need all theses intermediary composable such as 
decoratedLeading, Decoration, ContentWithIcon, etc

2023-02-27 09:14 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/atoms/GrapesButtonContentIcon.kt
> +}
Isn't it the same signature as Icon ? Why needing another Icon for GrapesButtonContent?

2023-02-28 13:57 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesButtonIcon.kt
> +    val isFillMaxWidthWithContent =
Done

2023-02-28 15:43 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/button/GrapesCoreButton.kt
> +
Ok done, I optimized composables.
For Icon, I need to put it inside a box to define a size a apply padding to it.

2023-03-03 09:08 UTC, kelianClerc approved these changes

2023-03-03 10:02 UTC, merged