feat(compose) Add Grapes Tag
Spendesk/grapes-android pull request #278
Opened 2023-10-18 14:24 UTC by jpbarbaud

# Add new Grapes Tap component

## Preview

| Type | Screenshot |
| :---: | ---|
| Error | ![Screenshot 2023-10-18 at 16 17 52](https://github.com/Spendesk/grapes-android/assets/112860634/916ceafa-9cdf-41f3-9033-f5345263eee5) |
| Warning | ![Screenshot 2023-10-18 at 16 17 56](https://github.com/Spendesk/grapes-android/assets/112860634/5331d088-e720-4ead-9448-328ac2a95a7c) |
| Info | ![Screenshot 2023-10-18 at 16 18 00](https://github.com/Spendesk/grapes-android/assets/112860634/89f7618f-1afc-405a-892c-122709c73dc2) |
| Success | ![Screenshot 2023-10-18 at 16 18 03](https://github.com/Spendesk/grapes-android/assets/112860634/7b17dcde-bf4d-4a33-b6fe-4cbacecb3a24) | 

## Usage

### Error
```kotlin
GrapesErrorTag(
    label = "Label",
    showIcon = true // Optional - true by default
)
```
### Warning
```kotlin
GrapesWarningTag(
    label = "Label",
    showIcon = true // Optional - true by default
)
```

### Info
```kotlin
GrapesInfoTag(
    label = "Label",
    showIcon = true // Optional - true by default
)
```
### Success
```kotlin
GrapesSuccessTag(
    label = "Label",
    showIcon = true // Optional - true by default
)
```

2023-10-18 15:20 UTC, kelianClerc requested changes

2023-10-18 15:20 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/tag/GrapesTag.kt
> +                            .size(GrapesTagDefaults.iconSize)
this does not define the size of the icon but the size of the container of the icon. Do you really need it?
If somewhere you put `GrapesTagIcon(iconRes = R.drawable.ic_error, contentDescription = "Error tag icon", modifier = Modifier.size(64.dp))` what happen?

2023-10-18 15:28 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/tag/GrapesTag.kt
> +                            .size(GrapesTagDefaults.iconSize)
![Screenshot 2023-10-18 at 17 27 58](https://github.com/Spendesk/grapes-android/assets/112860634/2e6afcb0-2163-454e-9ee7-ca8ee9b2c65a)

2023-10-18 15:40 UTC, jpbarbaud commented on library-compose/src/main/java/com/spendesk/grapes/compose/tag/GrapesTagDefaults.kt
> +    borderStoreColor: Color = GrapesTheme.colors.mainAlertLighter,
I tried to take advantage of the LocalContentColor.
I was inspired by the Material `TextFieldDefaults.textFieldColors()`.

2023-10-19 08:04 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/tag/GrapesTagDefaults.kt
> +    borderStoreColor: Color = GrapesTheme.colors.mainAlertLighter,
Check how the button is done. It's in fact the surface that defines the LocalContentColor so we should even have to add it ourselves

2023-10-19 14:53 UTC, kelianClerc approved these changes

2023-10-20 07:59 UTC, merged