Create amount list item
Spendesk/grapes-android pull request #321
Opened 2024-01-05 12:05 UTC by RomainGF

[Figma Grapes Mobile - ExpenseItem/SubscriptionItem/RequestItem](https://www.figma.com/file/HGkiY2FkV2iLycWll0CEe7wS/%F0%9F%8D%87-Mobile?type=design&node-id=14034-4759&mode=dev)
![Capture d’écran 2024-01-05 à 13 01 02](https://github.com/Spendesk/grapes-android/assets/24422094/a9f39d8b-cec8-4b47-90bc-cf68c182937d)
![Capture d’écran 2024-01-05 à 13 01 40](https://github.com/Spendesk/grapes-android/assets/24422094/7d06ba7c-bb95-401c-ba82-9a55677c0dbf)

[Figma Grapes Core - HighlightIcon](https://www.figma.com/file/Wy5r8f7tbdPL1oPmzxHakmck/%F0%9F%8D%87-Contents?type=design&node-id=3352-278&mode=dev)
![Capture d’écran 2024-01-05 à 13 01 27](https://github.com/Spendesk/grapes-android/assets/24422094/bb0144ad-d9cc-4e5a-8a44-84bb5a14726e)

2024-01-05 13:36 UTC, kelianClerc requested changes

2024-01-05 13:36 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/icons/GrapesHighlightIcon.kt
> +            .padding(GrapesTheme.dimensions.spacing1),
From what I see, there is no padding on figma for the container of the icon. It's a container with a fixed size that contains an icon with a fix size center in that container. Why did you added a padding here?

2024-01-05 13:36 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/logo/GrapesBadgedLogo.kt
> +    val supportedAlignments = remember { arrayOf(Alignment.TopEnd, Alignment.BottomEnd) }
why not as a const outside of the composable ?

2024-01-05 13:36 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/logo/GrapesBadgedLogo.kt
> +                    .size(GrapesTheme.dimensions.sizing4)
is the size necessary? Is it to constraint badge size? If yes, you're right we have to keep it

2024-01-05 13:36 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/listitem/GrapesAmountListItem.kt
> +            Row {
To validate with nico : 
For each Row, it might be necessary to constraint the text that has weight(1f) to a single line
I added excessively long values, they will most certainly never reach that lenght. Do we have to put maxWidth to it or not ? 

![Capture d’écran 2024-01-05 à 14 32 30](https://github.com/Spendesk/grapes-android/assets/26220096/35b54b40-0ae6-4985-8773-214ad9da8df7)


I think it's worth not putting a max width to be able to have this situation: 

![Capture d’écran 2024-01-05 à 14 34 43](https://github.com/Spendesk/grapes-android/assets/26220096/dfe86665-59b5-491f-b645-1d2d964452ab)

Anyway all this has to be decided by nico (it might be already spec in the figma component btw)

2024-01-05 13:36 UTC, kelianClerc commented on library-compose/src/main/java/com/spendesk/grapes/compose/listitem/GrapesAmountListItem.kt
> +            Row {
Adding a preview of these cases could be useful for QA + make sure we do not introduce regression on edge cases in the futur updates of this component

2024-01-05 14:51 UTC, RomainGF commented on library-compose/src/main/java/com/spendesk/grapes/compose/icons/GrapesHighlightIcon.kt
> +            .padding(GrapesTheme.dimensions.spacing1),
Yes unnecessary one

2024-01-05 14:54 UTC, RomainGF commented on library-compose/src/main/java/com/spendesk/grapes/compose/logo/GrapesBadgedLogo.kt
> +                    .size(GrapesTheme.dimensions.sizing4)
Yes so the badge can't oversize this

2024-01-08 08:22 UTC, RomainGF commented on library-compose/src/main/java/com/spendesk/grapes/compose/listitem/GrapesAmountListItem.kt
> +            Row {
I've checked with Nico and added previews 👍 
<img width="415" alt="Capture d’écran 2024-01-05 à 16 45 43" src="https://github.com/Spendesk/grapes-android/assets/24422094/a75eb567-a533-4800-b96b-155f69d86349">

2024-01-08 08:24 UTC, kelianClerc approved these changes

2024-01-08 08:29 UTC, merged