Task/aa 3297 create awaiting reimbursement item
Spendesk/grapes-android pull request #336
Opened 2024-01-30 14:46 UTC by Scythe14

![Screenshot 2024-01-30 at 15 42 03](https://github.com/Spendesk/grapes-android/assets/9486557/b10c5313-9a4d-45f4-8ed5-4176f4f12b4d)
![Screenshot 2024-01-30 at 15 05 26](https://github.com/Spendesk/grapes-android/assets/9486557/523aee25-9961-4252-92ef-0da1b3dbeb92)

2024-01-30 16:12 UTC, RomainGF requested changes

2024-01-30 16:12 UTC, RomainGF commented on library-compose/src/main/java/com/spendesk/grapes/compose/theme/Dimensions.kt
> +    val grapesStackSurface: Dp = 36.dp
This dimension is not intended to be reused elsewhere than in the composable, so it must stay at the composable level. We should try to keep only these dimensions here : https://www.figma.com/file/fiCb2Cltq1gJuByGKvxLNb/%F0%9F%8D%87--Design-Tokens?type=design&node-id=2978-20087&mode=design&t=AcLTEy1QplJFUZTk-4

2024-01-31 09:29 UTC, Scythe14 commented on library-compose/src/main/java/com/spendesk/grapes/compose/theme/Dimensions.kt
> +    val grapesStackSurface: Dp = 36.dp
trou

2024-01-31 13:37 UTC, RomainGF approved these changes

2024-01-31 13:39 UTC, merged