Task/cards selectors inputs messages
Spendesk/grapes-android pull request #4
Opened 2021-06-17 09:34 UTC by Scythe14

Some things there:
- Added a lot of new components in Inputs Messages and Selectors UI kit.
- Added those new components to the Sample app
- Move some components into new packages according to the UI Kit hierarchy.

You can run the sample to easily see those components. (Not even need to checkout but just see the app tester build ;) )

2021-07-01 07:53 UTC, Tweener requested changes
Great job for all these components! 🚀 🔥 

Nothing to say about the components themselves but 2 main things:
- Some component names: we might need to review some to be more accurate. 
- What's the difference between `SelectBlockCardView` and `PickerBlockIconCardView`?
Let me know what you think, we can also discuss it on Zoom!

2021-07-01 07:53 UTC, Tweener commented on library/src/main/java/com/spendesk/grapes/selectors/HeaderStatusIndicator.kt
> +            progressBarIds.add(progressBar.id)
Add a break line here, to separate the configuration of the `progressBar` to the addition into the list, so it's more readable.

2021-07-01 07:53 UTC, Tweener commented on sample/build.gradle
>      implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
You can check what has been done on [this PR](https://github.com/Spendesk/spendesk-android/pull/812/files#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R347-R354) to make sure we use the same libraries (version number, `-ktx`, remove `com.google.android.material:material`, etc.)

2021-07-01 09:48 UTC, Scythe14 commented on library/src/main/java/com/spendesk/grapes/extensions/EditTextExtensions.kt
> +fun AppCompatEditText.setupClearButtonWithAction(drawable: Drawable?) {
Yep, but mb some other people won't chose or will prefer another icon to put there, this always is the complicated line in Design system, should we enforce our drawable or mb let it configurable ?

2021-07-01 09:50 UTC, Scythe14 commented on library/src/main/java/com/spendesk/grapes/inputs/SearchInputMain.kt
> +class SearchInputMain : CardView {
Yes this one is poorly chose ... But in order to avoid spending too much time rethinking all the hierarchy and components name, I chose to use the namings in the UI kit for now, I scheduled a hierarchy and components name redesign at the end of the month after Mileage feature !

But to save you some time, namings are not really consistent

2021-07-01 09:52 UTC, Scythe14 commented on library/src/main/java/com/spendesk/grapes/list/item/ListItemView.kt
> +class ListItemView : ConstraintLayout {
Yep still the same naming issue ... I know, still letting the same name as the one provided by the UI Kit :/

2021-07-02 12:01 UTC, Scythe14 commented on library/src/main/java/com/spendesk/grapes/extensions/EditTextExtensions.kt
> +fun AppCompatEditText.setupClearButtonWithAction(drawable: Drawable?) {
Ok I removed the possibility. It is pretty easy to add it later if needed !

2021-07-02 12:03 UTC, Scythe14 commented on library/src/main/java/com/spendesk/grapes/inputs/SearchInputMain.kt
> +            // add the according style tint for compound drawables except for clear icon
Back to primary school I guess hahah yes, will do !

2021-07-02 12:06 UTC, Scythe14 commented on library/src/main/java/com/spendesk/grapes/selectors/HeaderStatusIndicator.kt
> +class HeaderStatusIndicator : ConstraintLayout {
There was not any name in the UI Kit, and I hate having chose "tor" suffix name but have not found another one :/
This one is tricky because I did not want to add some viewpager notion to the component as this could simply be a view where you want some bar and progress display, still it takes part of the future naming task I will do

2021-07-02 12:08 UTC, Scythe14 commented on library/src/main/java/com/spendesk/grapes/selectors/HeaderStatusIndicator.kt
> +            progressBarIds.add(progressBar.id)
yes ! Added a with function to better scope progressbar property settings as well

2021-07-02 13:36 UTC, Scythe14 commented on sample/build.gradle
>      implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
Will dig into that later as I told you 👍

2021-07-02 14:22 UTC, Tweener approved these changes

2021-07-02 14:59 UTC, merged