Create new panama bloc for request summary (Approver view) - PR 1
Spendesk/grapes-android pull request #5
Opened 2021-06-17 09:46 UTC by Tweener

2021-06-17 15:02 UTC, Scythe14 requested changes
Nice one 🔥 !
I have a tiny comment about ratio and I spotted a useless image also, I guess it was for test purposes maybe but you can remove it: `library/src/main/res/drawable/img_mileage_map_example.png`

Otherwise, would not be better to add the example in the sample application and so the test purpose `img_mileage_map_example` file  ?

2021-06-17 18:08 UTC, Tweener commented
> Nice one 🔥 !
> I have a tiny comment about ratio and I spotted a useless image also, I guess it was for test purposes maybe but you can remove it: `library/src/main/res/drawable/img_mileage_map_example.png`
> 
> Otherwise, would not be better to add the example in the sample application and so the test purpose `img_mileage_map_example` file ?

Yeah I agree it should be removed but my idea was to be able to see the map when you are in edit mode. Do you have any idea how to do that? Otherwise we don't see anything.

2021-06-17 18:46 UTC, Tweener commented on library/src/main/java/com/spendesk/grapes/component/content/summary/noneditable/SummaryBlockContentMapView.kt
> +        private const val MAP_IMAGE_HEIGHT_RATIO = 0.68 // Height is smaller than the width
I actually tried but it just doesn't work 🤷‍♂️  If you wanna take a look, go ahead!

2021-06-21 15:51 UTC, Scythe14 commented on library/src/main/java/com/spendesk/grapes/component/content/summary/noneditable/SummaryBlockContentMapView.kt
> +        private const val MAP_IMAGE_HEIGHT_RATIO = 0.68 // Height is smaller than the width
Hum weird, we can still merge this and check it later otherwise !

2021-06-21 16:23 UTC, Scythe14 commented
> > Nice one 🔥 !
> > I have a tiny comment about ratio and I spotted a useless image also, I guess it was for test purposes maybe but you can remove it: `library/src/main/res/drawable/img_mileage_map_example.png`
> > Otherwise, would not be better to add the example in the sample application and so the test purpose `img_mileage_map_example` file ?
> 
> Yeah I agree it should be removed but my idea was to be able to see the map when you are in edit mode. Do you have any idea how to do that? Otherwise we don't see anything.

Yep I guess, we might wait for the other merge and avoid conflicts and later add this in the sample app :)

2021-06-21 16:23 UTC, Scythe14 approved these changes

2021-06-22 06:03 UTC, merged