Add native keyboard propositions lookalike
Spendesk/grapes-android pull request #78
Opened 2022-03-31 08:07 UTC by kelianClerc

Add to grapes a view that looks like native keyboard propositions.

Naming and location of the component may be discussed though

https://user-images.githubusercontent.com/26220096/161007841-189e8f70-aef3-4f2d-963a-c91fccbf2139.mov

2022-03-31 09:30 UTC, kelianClerc commented on library/src/main/res/values/styles_selectors.xml
> +    ew
oups

2022-03-31 11:06 UTC, Tweener requested changes
A few things to change here:
- The naming `proposition` is not correct in English for what we need.
- The way of building the TextViews could be improved to avoid a possible de-sync between the list of TextViews created and the number of configuration.items requested.
- The usage of a custom `OnItemClickedListener ` to avoid.

On another topic (already started on Slack): whether or not this view should be directly included in the `NumberKeyboard`, as an optional view.
I would prefer to enforce this `KeyboardPropositionsView` as part of the `NumberKeyboard` for the following reasons:
- Since this view is meant to be always linked to a keyboard, it would make sense that it is part of the `NumberKeyboard`, as optional, with the ability to configure it. From the point of view of our Design System (DS), we don't want to let the flexibility to the people using it to do whatever they want. On the contrary, we want to enforce this behavior of having suggestions specific to a keyboard.
In other words: `NumberKeyboard` remains the main atom and `KeyboardPropositionsView` is a molecule that is part of it. 
- We already have a view for a selector of items, outside of a keyboard, check: `PickerCardListView`. So for sure, this `KeyboardPropositionsView` will not be reused outside of the context of a keyboard.

2022-03-31 12:35 UTC, kelianClerc commented on library/src/main/java/com/spendesk/grapes/selectors/KeyboardPropositionsView.kt
> +        val maxItemsPerLine: Int = DEFAULT_MAX_ITEMS_PER_LINE
Or I can simply remove that and let all items in the same line. It will be to the caller to make sure only what he wants is displayed

2022-03-31 12:44 UTC, Tweener commented on library/src/main/java/com/spendesk/grapes/selectors/KeyboardPropositionsView.kt
> +        val maxItemsPerLine: Int = DEFAULT_MAX_ITEMS_PER_LINE
>use val itemsToShow = configuration.items.take(configuration.maxItems)

Yeah that would be perfect. It's the responsibility of our DS to ensure it works properly no matter what the user asks for.

2022-03-31 14:47 UTC, kelianClerc commented on library/src/main/java/com/spendesk/grapes/NumberKeyboard.kt
> +    data class Suggestions(
`Suggestion` witout s

2022-03-31 18:03 UTC, Tweener requested changes
That much better with the suggestions within the keyboard view! 🔥 

A few things left to change and it'll be good!

2022-03-31 18:03 UTC, Tweener commented on library/src/main/java/com/spendesk/grapes/selectors/KeyboardSuggestionsView.kt
> +        val maxItems: Int = DEFAULT_MAX_ITEMS
Actually, I'm wondering if we really need this variable as configuration.
As the caller can pass a list of suggestions, the number of items is the max between that list size and DEFAULT_MAX_ITEMS.
Wdyt?

2022-04-01 07:52 UTC, kelianClerc commented on library/src/main/java/com/spendesk/grapes/selectors/KeyboardSuggestionsView.kt
> +    fun updateItemTextAppearance(@StyleRes textAppearanceRes: Int) {
This class is internal to the DS because KeyboardSuggestionsView is now `internal`. I would prefer to keep it public for other mollecules using it to be able to customize it

2022-04-01 07:59 UTC, kelianClerc commented on library/src/main/java/com/spendesk/grapes/selectors/KeyboardSuggestionsView.kt
> +        val maxItems: Int = DEFAULT_MAX_ITEMS
You're right

2022-04-01 08:04 UTC, Tweener commented on library/src/main/java/com/spendesk/grapes/selectors/KeyboardSuggestionsView.kt
> +    fun updateItemTextAppearance(@StyleRes textAppearanceRes: Int) {
(Open question, no need to change now) Shouldn't we do the other way in a Design System? Restrict the customization and if one day we need it, "open" it to external molecules/atoms?
Maybe @Scythe14 as some inputs on it as well?

2022-04-01 08:15 UTC, Tweener commented on library/src/main/java/com/spendesk/grapes/NumberKeyboard.kt
> +        suggestions?.let { this.suggestions.addAll(it) }
>When passing null suggestions are cleared and configuration is empty so suggestions are all removed.

Haha yes indeed, I misread the line and thought the clear was done in the `.let { ... }` 😅

2022-04-01 11:45 UTC, kelianClerc commented on library/src/main/java/com/spendesk/grapes/selectors/KeyboardSuggestionsView.kt
> +    fun updateItemTextAppearance(@StyleRes textAppearanceRes: Int) {
Here it needs to be opened because the keyboard can be light or dark. 
But in most case, in my opinion, you're right, design system should be "as restrictive as possible" in term of style and appearance to make sure look and feel is consistent all over the app. 
Curious to hear @Scythe14 opinion too

2022-04-01 13:16 UTC, Tweener approved these changes

2022-04-01 13:31 UTC, merged